SELECT * FROM public.etiquetas
ORDER BY id_etiqueta ASC;
INSERT INTO etiquetas (nombre_etiqueta) VALUES
('Tecnología'),
('Programación'),
('Salud'),
('Educación'),
('Deportes'),
('Entretenimiento'),
('Ciencia'),
('Viajes'),
('Arte'),
('Música'),
('Cultura'),
('Moda'),
('Cine'),
('Fotografía'),
('Literatura'),
('Gastronomía'),
('Historia'),
('Política'),
('Economía'),
('Negocios'),
('Medio Ambiente'),
('Animales'),
('Sociedad'),
('Psicología'),
('Filosofía'),
('Religión'),
('Videojuegos'),
('Automóviles'),
('Marketing'),
('Redes Sociales');
